import 'dotenv/config'
import { PrismaClient } from '../src/generated/prisma/client'
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3'
import path from 'node:path'

const dbPath = path.resolve(process.cwd(), 'prisma/dev.db')
const adapter = new PrismaBetterSqlite3({ url: `file:${dbPath}` })
const prisma = new PrismaClient({ adapter } as any)

function slug(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

const exercises = [
  // ─── BARBELL COMPOUND ────────────────────────────────────
  {
    name: 'Back Squat',
    type: 'BARBELL',
    category: 'COMPOUND',
    movementPattern: 'SQUAT',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'traps'],
    equipment: ['barbell', 'rack'],
    cues: 'Chest up, knees out, hip crease below parallel',
  },
  {
    name: 'Front Squat',
    type: 'BARBELL',
    category: 'COMPOUND',
    movementPattern: 'SQUAT',
    primaryMuscles: ['quads', 'core'],
    secondaryMuscles: ['glutes', 'upper_back'],
    equipment: ['barbell', 'rack'],
    cues: 'Elbows high, upright torso, knees tracking toes',
  },
  {
    name: 'Deadlift',
    type: 'BARBELL',
    category: 'COMPOUND',
    movementPattern: 'HINGE',
    primaryMuscles: ['hamstrings', 'glutes', 'back'],
    secondaryMuscles: ['traps', 'forearms', 'core'],
    equipment: ['barbell'],
    cues: 'Bar over mid-foot, lats engaged, drive floor away',
  },
  {
    name: 'Romanian Deadlift',
    type: 'BARBELL',
    category: 'ACCESSORY',
    movementPattern: 'HINGE',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['back', 'core'],
    equipment: ['barbell'],
    cues: 'Hip hinge, slight knee bend, feel hamstring stretch',
  },
  {
    name: 'Sumo Deadlift',
    type: 'BARBELL',
    category: 'COMPOUND',
    movementPattern: 'HINGE',
    primaryMuscles: ['glutes', 'quads', 'hamstrings'],
    secondaryMuscles: ['back', 'traps'],
    equipment: ['barbell'],
  },
  {
    name: 'Bench Press',
    type: 'BARBELL',
    category: 'COMPOUND',
    movementPattern: 'HORIZONTAL_PUSH',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['barbell', 'bench'],
    cues: 'Arch, retract scapula, bar to lower chest, drive through',
  },
  {
    name: 'Overhead Press',
    type: 'BARBELL',
    category: 'COMPOUND',
    movementPattern: 'VERTICAL_PUSH',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'traps', 'core'],
    equipment: ['barbell'],
    cues: 'Bar below chin, squeeze glutes and abs, press to lockout',
  },
  {
    name: 'Barbell Row',
    type: 'BARBELL',
    category: 'COMPOUND',
    movementPattern: 'HORIZONTAL_PULL',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps', 'traps', 'rear_delts'],
    equipment: ['barbell'],
    cues: '45-degree torso, pull to lower chest, elbows back',
  },
  {
    name: 'Pendlay Row',
    type: 'BARBELL',
    category: 'COMPOUND',
    movementPattern: 'HORIZONTAL_PULL',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps', 'traps'],
    equipment: ['barbell'],
    cues: 'Parallel torso, explosive pull, reset each rep',
  },
  {
    name: 'Good Morning',
    type: 'BARBELL',
    category: 'ACCESSORY',
    movementPattern: 'HINGE',
    primaryMuscles: ['hamstrings', 'glutes', 'back'],
    secondaryMuscles: ['core'],
    equipment: ['barbell', 'rack'],
  },
  {
    name: 'Pause Squat',
    type: 'BARBELL',
    category: 'COMPOUND',
    movementPattern: 'SQUAT',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'hamstrings'],
    equipment: ['barbell', 'rack'],
    cues: '3-second pause at bottom, stay tight',
  },
  {
    name: 'Incline Bench Press',
    type: 'BARBELL',
    category: 'ACCESSORY',
    movementPattern: 'HORIZONTAL_PUSH',
    primaryMuscles: ['chest', 'shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['barbell', 'bench'],
  },
  {
    name: 'Close-Grip Bench Press',
    type: 'BARBELL',
    category: 'ACCESSORY',
    movementPattern: 'HORIZONTAL_PUSH',
    primaryMuscles: ['triceps', 'chest'],
    secondaryMuscles: ['shoulders'],
    equipment: ['barbell', 'bench'],
  },

  // ─── OLYMPIC LIFTS ────────────────────────────────────────
  {
    name: 'Power Clean',
    type: 'BARBELL',
    category: 'OLYMPIC',
    movementPattern: 'OLYMPIC',
    primaryMuscles: ['quads', 'glutes', 'traps', 'shoulders'],
    secondaryMuscles: ['hamstrings', 'back', 'core'],
    equipment: ['barbell'],
    cues: 'Triple extension, high pull, fast elbows under',
  },
  {
    name: 'Clean & Jerk',
    type: 'BARBELL',
    category: 'OLYMPIC',
    movementPattern: 'OLYMPIC',
    primaryMuscles: ['quads', 'glutes', 'traps', 'shoulders', 'triceps'],
    secondaryMuscles: ['hamstrings', 'back', 'core'],
    equipment: ['barbell'],
  },
  {
    name: 'Power Snatch',
    type: 'BARBELL',
    category: 'OLYMPIC',
    movementPattern: 'OLYMPIC',
    primaryMuscles: ['quads', 'glutes', 'traps', 'shoulders'],
    secondaryMuscles: ['hamstrings', 'back', 'core'],
    equipment: ['barbell'],
  },
  {
    name: 'Snatch',
    type: 'BARBELL',
    category: 'OLYMPIC',
    movementPattern: 'OLYMPIC',
    primaryMuscles: ['quads', 'glutes', 'traps', 'shoulders'],
    secondaryMuscles: ['hamstrings', 'back', 'core'],
    equipment: ['barbell'],
  },
  {
    name: 'Hang Power Clean',
    type: 'BARBELL',
    category: 'OLYMPIC',
    movementPattern: 'OLYMPIC',
    primaryMuscles: ['quads', 'glutes', 'traps'],
    secondaryMuscles: ['hamstrings', 'back'],
    equipment: ['barbell'],
  },
  {
    name: 'Hang Snatch',
    type: 'BARBELL',
    category: 'OLYMPIC',
    movementPattern: 'OLYMPIC',
    primaryMuscles: ['quads', 'glutes', 'traps'],
    secondaryMuscles: ['hamstrings', 'back'],
    equipment: ['barbell'],
  },
  {
    name: 'Push Jerk',
    type: 'BARBELL',
    category: 'OLYMPIC',
    movementPattern: 'VERTICAL_PUSH',
    primaryMuscles: ['shoulders', 'triceps', 'quads'],
    secondaryMuscles: ['core', 'traps'],
    equipment: ['barbell'],
  },
  {
    name: 'Thruster',
    type: 'BARBELL',
    category: 'OLYMPIC',
    movementPattern: 'SQUAT',
    primaryMuscles: ['quads', 'shoulders', 'triceps'],
    secondaryMuscles: ['glutes', 'core'],
    equipment: ['barbell'],
    cues: 'Front squat + push press in one fluid movement',
  },

  // ─── DUMBBELL ACCESSORIES ─────────────────────────────────
  {
    name: 'Dumbbell Romanian Deadlift',
    type: 'DUMBBELL',
    category: 'ACCESSORY',
    movementPattern: 'HINGE',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['back', 'core'],
    equipment: ['dumbbells'],
  },
  {
    name: 'Dumbbell Bench Press',
    type: 'DUMBBELL',
    category: 'ACCESSORY',
    movementPattern: 'HORIZONTAL_PUSH',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['dumbbells', 'bench'],
  },
  {
    name: 'Dumbbell Row',
    type: 'DUMBBELL',
    category: 'ACCESSORY',
    movementPattern: 'HORIZONTAL_PULL',
    primaryMuscles: ['lats', 'back'],
    secondaryMuscles: ['biceps', 'rear_delts'],
    equipment: ['dumbbells', 'bench'],
  },
  {
    name: 'Dumbbell Lateral Raise',
    type: 'DUMBBELL',
    category: 'ACCESSORY',
    movementPattern: 'VERTICAL_PUSH',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['traps'],
    equipment: ['dumbbells'],
  },
  {
    name: 'Dumbbell Curl',
    type: 'DUMBBELL',
    category: 'ACCESSORY',
    movementPattern: 'VERTICAL_PULL',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbells'],
  },
  {
    name: 'Dumbbell Overhead Press',
    type: 'DUMBBELL',
    category: 'ACCESSORY',
    movementPattern: 'VERTICAL_PUSH',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'traps'],
    equipment: ['dumbbells'],
  },
  {
    name: 'Dumbbell Lunges',
    type: 'DUMBBELL',
    category: 'ACCESSORY',
    movementPattern: 'SQUAT',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves'],
    equipment: ['dumbbells'],
  },
  {
    name: 'Goblet Squat',
    type: 'KETTLEBELL',
    category: 'ACCESSORY',
    movementPattern: 'SQUAT',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'upper_back'],
    equipment: ['kettlebell'],
    cues: 'Hold at chest, elbows in, deep squat',
  },
  {
    name: 'Kettlebell Swing',
    type: 'KETTLEBELL',
    category: 'ACCESSORY',
    movementPattern: 'HINGE',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['back', 'shoulders', 'core'],
    equipment: ['kettlebell'],
    cues: 'Hip drive, not a squat. Keep spine neutral.',
  },
  {
    name: 'Kettlebell Turkish Get-Up',
    type: 'KETTLEBELL',
    category: 'ACCESSORY',
    movementPattern: 'ROTATION',
    primaryMuscles: ['shoulders', 'core'],
    secondaryMuscles: ['glutes', 'quads'],
    equipment: ['kettlebell'],
  },

  // ─── BODYWEIGHT / GYMNASTIC ───────────────────────────────
  {
    name: 'Pull-Up',
    type: 'BODYWEIGHT',
    category: 'COMPOUND',
    movementPattern: 'VERTICAL_PULL',
    primaryMuscles: ['lats', 'back'],
    secondaryMuscles: ['biceps', 'core'],
    equipment: ['pull-up bar'],
    cues: 'Full ROM, chest to bar, controlled descent',
  },
  {
    name: 'Chin-Up',
    type: 'BODYWEIGHT',
    category: 'COMPOUND',
    movementPattern: 'VERTICAL_PULL',
    primaryMuscles: ['lats', 'biceps'],
    secondaryMuscles: ['back', 'core'],
    equipment: ['pull-up bar'],
  },
  {
    name: 'Muscle-Up',
    type: 'BODYWEIGHT',
    category: 'GYMNASTIC',
    movementPattern: 'VERTICAL_PULL',
    primaryMuscles: ['lats', 'chest', 'triceps'],
    secondaryMuscles: ['shoulders', 'core', 'back'],
    equipment: ['pull-up bar'],
    cues: 'Kip or strict, false grip, aggressive pull to transition',
  },
  {
    name: 'Ring Muscle-Up',
    type: 'BODYWEIGHT',
    category: 'GYMNASTIC',
    movementPattern: 'VERTICAL_PULL',
    primaryMuscles: ['lats', 'chest', 'triceps'],
    secondaryMuscles: ['shoulders', 'core'],
    equipment: ['rings'],
  },
  {
    name: 'Handstand Push-Up',
    type: 'BODYWEIGHT',
    category: 'GYMNASTIC',
    movementPattern: 'VERTICAL_PUSH',
    primaryMuscles: ['shoulders', 'triceps'],
    secondaryMuscles: ['traps', 'core'],
    equipment: ['wall'],
    cues: 'Head between hands, lower to ear level, press to lockout',
  },
  {
    name: 'Ring Dip',
    type: 'BODYWEIGHT',
    category: 'GYMNASTIC',
    movementPattern: 'HORIZONTAL_PUSH',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders'],
    equipment: ['rings'],
  },
  {
    name: 'Bar Dip',
    type: 'BODYWEIGHT',
    category: 'COMPOUND',
    movementPattern: 'HORIZONTAL_PUSH',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders'],
    equipment: ['parallel bars'],
  },
  {
    name: 'Toes-to-Bar',
    type: 'BODYWEIGHT',
    category: 'GYMNASTIC',
    movementPattern: 'ROTATION',
    primaryMuscles: ['core'],
    secondaryMuscles: ['lats', 'hip_flexors'],
    equipment: ['pull-up bar'],
    cues: 'Hollow/arch kip, touch toes at top, feet together',
  },
  {
    name: 'Kipping Pull-Up',
    type: 'BODYWEIGHT',
    category: 'GYMNASTIC',
    movementPattern: 'VERTICAL_PULL',
    primaryMuscles: ['lats', 'back'],
    secondaryMuscles: ['core', 'shoulders'],
    equipment: ['pull-up bar'],
  },
  {
    name: 'Butterfly Pull-Up',
    type: 'BODYWEIGHT',
    category: 'GYMNASTIC',
    movementPattern: 'VERTICAL_PULL',
    primaryMuscles: ['lats', 'back'],
    secondaryMuscles: ['core', 'shoulders'],
    equipment: ['pull-up bar'],
  },
  {
    name: 'Push-Up',
    type: 'BODYWEIGHT',
    category: 'ACCESSORY',
    movementPattern: 'HORIZONTAL_PUSH',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders', 'core'],
    equipment: [],
  },
  {
    name: 'Pistol Squat',
    type: 'BODYWEIGHT',
    category: 'GYMNASTIC',
    movementPattern: 'SQUAT',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'hip_flexors'],
    equipment: [],
    cues: 'Single leg squat to full depth, keep heel down',
  },
  {
    name: 'Box Jump',
    type: 'BODYWEIGHT',
    category: 'METCON',
    movementPattern: 'SQUAT',
    primaryMuscles: ['quads', 'glutes', 'calves'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['plyo box'],
    cues: 'Full hip/knee extension at top, step down',
  },
  {
    name: 'Burpee',
    type: 'BODYWEIGHT',
    category: 'METCON',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['quads', 'chest', 'shoulders'],
    secondaryMuscles: ['core', 'triceps', 'glutes'],
    equipment: [],
  },
  {
    name: 'Burpee Box Jump Over',
    type: 'BODYWEIGHT',
    category: 'METCON',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['quads', 'chest', 'glutes'],
    secondaryMuscles: ['core', 'calves'],
    equipment: ['plyo box'],
  },
  {
    name: 'Double Under',
    type: 'CARDIO',
    category: 'CARDIO',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['calves', 'shoulders'],
    secondaryMuscles: ['core', 'forearms'],
    equipment: ['jump rope'],
    cues: 'Tight wrists, stay on balls of feet, slight jump',
  },
  {
    name: 'Single Under',
    type: 'CARDIO',
    category: 'CARDIO',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['shoulders'],
    equipment: ['jump rope'],
  },
  {
    name: 'Wall Ball',
    type: 'BODYWEIGHT',
    category: 'METCON',
    movementPattern: 'SQUAT',
    primaryMuscles: ['quads', 'shoulders'],
    secondaryMuscles: ['glutes', 'core', 'triceps'],
    equipment: ['medicine ball', 'wall'],
    cues: 'Full squat, explode up, throw to target (10ft/9ft)',
  },

  // ─── CARDIO ───────────────────────────────────────────────
  {
    name: 'Row (Erg)',
    type: 'CARDIO',
    category: 'CARDIO',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['back', 'legs'],
    secondaryMuscles: ['core', 'biceps'],
    equipment: ['rowing machine'],
    cues: 'Drive legs, hinge back, pull elbows',
  },
  {
    name: 'Assault Bike',
    type: 'CARDIO',
    category: 'CARDIO',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['quads', 'chest', 'shoulders'],
    secondaryMuscles: ['hamstrings', 'back'],
    equipment: ['assault bike'],
  },
  {
    name: 'Ski Erg',
    type: 'CARDIO',
    category: 'CARDIO',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['lats', 'core', 'shoulders'],
    secondaryMuscles: ['triceps', 'back'],
    equipment: ['ski erg'],
  },
  {
    name: 'Run',
    type: 'CARDIO',
    category: 'CARDIO',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['quads', 'hamstrings', 'calves'],
    secondaryMuscles: ['glutes', 'core'],
    equipment: [],
  },
  {
    name: 'Bike (Outdoor/Erg)',
    type: 'CARDIO',
    category: 'CARDIO',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['quads', 'hamstrings'],
    secondaryMuscles: ['calves', 'glutes'],
    equipment: ['bike'],
  },

  // ─── CABLE & MACHINE ACCESSORIES ─────────────────────────
  {
    name: 'Cable Row',
    type: 'CABLE',
    category: 'ACCESSORY',
    movementPattern: 'HORIZONTAL_PULL',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps', 'rear_delts'],
    equipment: ['cable machine'],
  },
  {
    name: 'Cable Tricep Pushdown',
    type: 'CABLE',
    category: 'ACCESSORY',
    movementPattern: 'VERTICAL_PUSH',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['cable machine'],
  },
  {
    name: 'Cable Lat Pulldown',
    type: 'CABLE',
    category: 'ACCESSORY',
    movementPattern: 'VERTICAL_PULL',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'back'],
    equipment: ['cable machine'],
  },
  {
    name: 'Face Pull',
    type: 'CABLE',
    category: 'ACCESSORY',
    movementPattern: 'HORIZONTAL_PULL',
    primaryMuscles: ['rear_delts', 'traps'],
    secondaryMuscles: ['shoulders', 'biceps'],
    equipment: ['cable machine'],
    cues: 'Pull to face, external rotation, elbows above wrists',
  },
  {
    name: 'Leg Press',
    type: 'MACHINE',
    category: 'ACCESSORY',
    movementPattern: 'SQUAT',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['leg press machine'],
  },
  {
    name: 'Leg Curl',
    type: 'MACHINE',
    category: 'ACCESSORY',
    movementPattern: 'HINGE',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    equipment: ['leg curl machine'],
  },

  // ─── BENCHMARK WODs ───────────────────────────────────────
  {
    name: 'Fran',
    type: 'METCON',
    category: 'METCON',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['shoulders', 'quads', 'lats'],
    secondaryMuscles: ['core', 'triceps'],
    equipment: ['barbell', 'pull-up bar'],
    description: '21-15-9: Thruster (42.5/30kg) + Pull-Ups',
    cues: 'RX: 42.5kg/95lb thrusters, pull-ups',
  },
  {
    name: 'Grace',
    type: 'METCON',
    category: 'METCON',
    movementPattern: 'OLYMPIC',
    primaryMuscles: ['quads', 'shoulders', 'glutes'],
    secondaryMuscles: ['traps', 'core'],
    equipment: ['barbell'],
    description: '30 Clean & Jerks for time (60/43kg)',
  },
  {
    name: 'Helen',
    type: 'METCON',
    category: 'METCON',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['quads', 'back', 'core'],
    secondaryMuscles: ['glutes', 'shoulders'],
    equipment: ['kettlebell', 'pull-up bar'],
    description: '3 rounds: 400m run, 21 KB swings (24/16kg), 12 pull-ups',
  },
  {
    name: 'Cindy',
    type: 'METCON',
    category: 'METCON',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['chest', 'lats', 'quads'],
    secondaryMuscles: ['core', 'triceps', 'biceps'],
    equipment: ['pull-up bar'],
    description: '20 min AMRAP: 5 pull-ups, 10 push-ups, 15 air squats',
  },
  {
    name: 'Murph',
    type: 'METCON',
    category: 'METCON',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['quads', 'chest', 'lats'],
    secondaryMuscles: ['shoulders', 'core', 'glutes'],
    equipment: ['pull-up bar', 'weight vest'],
    description: '1 mile run, 100 pull-ups, 200 push-ups, 300 squats, 1 mile run (with 20lb vest)',
  },
  {
    name: 'Isabel',
    type: 'METCON',
    category: 'METCON',
    movementPattern: 'OLYMPIC',
    primaryMuscles: ['quads', 'glutes', 'traps'],
    secondaryMuscles: ['shoulders', 'back'],
    equipment: ['barbell'],
    description: '30 Snatches for time (60/43kg)',
  },
]

async function main() {
  console.log('Seeding exercise library...')

  let created = 0
  let skipped = 0

  for (const ex of exercises) {
    const existing = await prisma.exercise.findUnique({ where: { name: ex.name } })
    if (existing) {
      skipped++
      continue
    }

    await prisma.exercise.create({
      data: {
        name: ex.name,
        slug: slug(ex.name),
        type: ex.type,
        category: ex.category,
        movementPattern: ex.movementPattern,
        primaryMuscles: JSON.stringify(ex.primaryMuscles),
        secondaryMuscles: JSON.stringify(ex.secondaryMuscles ?? []),
        equipment: JSON.stringify(ex.equipment ?? []),
        description: ex.description,
        cues: ex.cues,
        isCustom: false,
      },
    })
    created++
  }

  console.log(`✓ ${created} exercises created, ${skipped} already existed`)
  console.log('Seed complete!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
